/**
 * ToDo Application API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ステータスIDを変換してステータスを表示する
 */
export type StatusIdEnum = 1 | 2 | 3;

export const StatusIdEnum = {
    NUMBER_1: 1 as StatusIdEnum,
    NUMBER_2: 2 as StatusIdEnum,
    NUMBER_3: 3 as StatusIdEnum
};

