/**
 * ToDo Application API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusIdEnum } from './status-id-enum';


export interface TaskGetResponseDto { 
    /**
     * UUID
     */
    id: string;
    /**
     * タイトル
     */
    title: string;
    /**
     * 詳細
     */
    description?: string | null;
    /**
     * 締切日
     */
    dueDate?: string | null;
    statusId: StatusIdEnum;
    /**
     * 作成日時
     */
    createdAt?: string | null;
    /**
     * 更新日時
     */
    updatedAt?: string | null;
}
export namespace TaskGetResponseDto {
}


