/**
 * ToDo Application API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusIdEnum } from './status-id-enum';


export interface TaskPostRequestDto { 
    /**
     * タイトル
     */
    title: string;
    /**
     * 詳細
     */
    description?: string | null;
    /**
     * 締切日
     */
    dueDate?: string | null;
    statusId?: StatusIdEnum;
}
export namespace TaskPostRequestDto {
}


