/**
 * ToDo Application API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusIdEnum } from './status-id-enum';


export interface TaskGetResponseDto { 
    /**
     * タイトル
     */
    Title: string;
    /**
     * 詳細
     */
    Description?: string;
    /**
     * 締切日
     */
    DueDate?: string;
    StatusId?: StatusIdEnum;
    /**
     * 作成日時
     */
    CreatedAt?: string;
    /**
     * 更新日時
     */
    UpdatedAt?: string;
}
export namespace TaskGetResponseDto {
}


