/**
 * ToDo Application API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskCreate { 
    /**
     * タイトル
     */
    Title: string;
    /**
     * 詳細
     */
    Description?: string;
    /**
     * 締切日
     */
    DueDate?: string;
    /**
     * ステータスIDを変換してステータスを表示する
     */
    StatusId?: TaskCreate.StatusIdEnum;
}
export namespace TaskCreate {
    export type StatusIdEnum = '0' | '1' | '2';
    export const StatusIdEnum = {
        _0: '0' as StatusIdEnum,
        _1: '1' as StatusIdEnum,
        _2: '2' as StatusIdEnum
    };
}


