/*
 * ToDo Application API
 *
 * ToDoアプリのAPI設計
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class TaskPutRequestDto : IEquatable<TaskPutRequestDto>
    {
        /// <summary>
        /// タイトル
        /// </summary>
        /// <value>タイトル</value>
        /* <example>本日のタスク</example> */
        [Required]
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// 詳細
        /// </summary>
        /// <value>詳細</value>
        /* <example>タスクの詳細</example> */
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// 締切日
        /// </summary>
        /// <value>締切日</value>
        /* <example>Mon Nov 18 00:00:00 UTC 2024</example> */
        [DataMember(Name = "dueDate", EmitDefaultValue = true)]
        public DateOnly? DueDate { get; set; }

        /// <summary>
        /// Gets or Sets StatusId
        /// </summary>
        [Required]
        [DataMember(Name = "statusId", EmitDefaultValue = true)]
        public StatusIdEnum StatusId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaskPutRequestDto {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  StatusId: ").Append(StatusId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TaskPutRequestDto)obj);
        }

        /// <summary>
        /// Returns true if TaskPutRequestDto instances are equal
        /// </summary>
        /// <param name="other">Instance of TaskPutRequestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskPutRequestDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) &&
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) &&
                (
                    DueDate == other.DueDate ||
                    DueDate != null &&
                    DueDate.Equals(other.DueDate)
                ) &&
                (
                    StatusId == other.StatusId ||

                    StatusId.Equals(other.StatusId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                if (DueDate != null)
                    hashCode = hashCode * 59 + DueDate.GetHashCode();

                hashCode = hashCode * 59 + StatusId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TaskPutRequestDto left, TaskPutRequestDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TaskPutRequestDto left, TaskPutRequestDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
