<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- <Nullable>enable</Nullable> -->
  </PropertyGroup>

  <!-- プロジェクト間参照  -->
  <ItemGroup>
    <ProjectReference Include="..\ToDoApp.Domain\ToDoApp.Domain.csproj" />
  </ItemGroup>

  <!-- NuGet パッケージ参照 -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.5" />
  </ItemGroup>

</Project>
