/*
 * ToDo Application API
 *
 * ToDoアプリのAPI設計
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class TasksApiController : ControllerBase
    { 
        /// <summary>
        /// タスク削除
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpDelete]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("Delete")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponseDto), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponseDto), description: "404 Not Found")]
        public virtual Task<IActionResult> Delete([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponseDto));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponseDto));

            throw new NotImplementedException();
        }

        /// <summary>
        /// タスク1件取得
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpGet]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("Get")]
        [SwaggerResponse(statusCode: 200, type: typeof(TaskGetResponseDto), description: "200 OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponseDto), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponseDto), description: "404 Not Found")]
        public virtual Task<IActionResult> Get([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(TaskGetResponseDto));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponseDto));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponseDto));
            string exampleJson = null;
            exampleJson = "{\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n}";
            exampleJson = "{\n  \"code\" : \"code\",\n  \"message\" : \"message\"\n}";
            exampleJson = "{\n  \"code\" : \"code\",\n  \"message\" : \"message\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<TaskGetResponseDto>(exampleJson)
            : default(TaskGetResponseDto);
            //TODO: Change the data returned
            return Task.FromResult<IActionResult>(new ObjectResult(example));
        }

        /// <summary>
        /// タスク一覧取得
        /// </summary>
        /// <remarks>0件のときは空の配列</remarks>
        /// <response code="200">200 OK</response>
        [HttpGet]
        [Route("/api/v1/tasks")]
        [ValidateModelState]
        [SwaggerOperation("Gets")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<TaskGetResponseDto>), description: "200 OK")]
        public virtual Task<IActionResult> Gets()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<TaskGetResponseDto>));
            string exampleJson = null;
            exampleJson = "[ {\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n}, {\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<TaskGetResponseDto>>(exampleJson)
            : default(List<TaskGetResponseDto>);
            //TODO: Change the data returned
            return Task.FromResult<IActionResult>(new ObjectResult(example));
        }

        /// <summary>
        /// タスク新規作成
        /// </summary>
        /// <param name="taskPostRequestDto"></param>
        /// <response code="201">201 Created</response>
        [HttpPost]
        [Route("/api/v1/tasks")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("Post")]
        public virtual Task<IActionResult> Post([FromBody]TaskPostRequestDto taskPostRequestDto)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            throw new NotImplementedException();
        }

        /// <summary>
        /// タスク更新
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpPut]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("Put")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponseDto), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponseDto), description: "404 Not Found")]
        public virtual Task<IActionResult> Put([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponseDto));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponseDto));

            throw new NotImplementedException();
        }
    }
}
