/*
 * ToDo Application API
 *
 * ToDoアプリのAPI設計
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class UsersApiController : ControllerBase
    { 
        /// <summary>
        /// ユーザー情報取得
        /// </summary>
        /// <param name="userId">取得するユーザーのUUID</param>
        /// <response code="200">ユーザー情報を正常に取得した</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpGet]
        [Route("/api/v1/users/{userId}")]
        [Authorize]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(UserGetResponseDto))]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponseDto))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponseDto))]
        public abstract Task<IActionResult> GetUser([FromRoute (Name = "userId")][Required]Guid userId);

        /// <summary>
        /// ユーザー新規登録
        /// </summary>
        /// <param name="userPostRequestDto"></param>
        /// <response code="201">ユーザーが正常に作成された</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="409">409 Conflict</response>
        [HttpPost]
        [Route("/api/v1/users")]
        [Authorize]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponseDto))]
        [ProducesResponseType(statusCode: 409, type: typeof(ErrorResponseDto))]
        public abstract Task<IActionResult> PostUser([FromBody]UserPostRequestDto userPostRequestDto);
    }
}
