version: '3.0'
services:

  # https://github.com/openapitools/openapi-generator-cli
  # ASP.NET Core Web API用
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./../src/apps/backend/src:/local
      - ./openapi.yml:/local/OpenApiGenerator/openapi.yml
    # https://openapi-generator.tech/docs/usage#generate
    command: generate -g aspnetcore -i local/OpenApiGenerator/openapi.yml -o local/OpenApiGenerator --additional-properties=aspnetCoreVersion=8.0,swashbuckleVersion=6.4.0,buildTarget=library,isLibrary=true,operationModifier=abstract,operationResultTask=true --skip-overwrite
    # command: >
    #   sh -c "
    #   rm -rf /local/OpenApiGenerator/src/Org.OpenAPITools/Controllers/* /local/OpenApiGenerator/src/Org.OpenAPITools/Models/* && generate -g aspnetcore -i local/OpenApiGenerator/openapi.yml -o local/OpenApiGenerator --additional-properties=aspnetCoreVersion=8.0,swashbuckleVersion=6.4.0,buildTarget=library,isLibrary=true,operationModifier=abstract,operationResultTask=true --skip-overwrite"

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   volumes:
  #     - ./openapi.yml:/usr/share/nginx/html/openapi.yml
  #   environment:
  #     API_URL: openapi.yml
  #   ports:
  #     - "8001:8080"

  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   ports:
  #     - "8002:8080"
