# 参考
# https://qiita.com/KNR109/items/7e094dba6bcf37ed73cf

openapi: 3.0.3

info:
  title: ToDo Application API
  description: ToDoアプリのAPI設計
  version: 1.0.0
  # license:
  # name:

servers:
  - url: https://localhost:3000/api/v1
    description: 開発環境
  - url: https://todo-app.com/api/v1
    description: 本番環境

tags:
  - name: tasks
    description: タスクに関連する操作。一覧取得、1件取得、新規作成、更新、削除が含まれる。

paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: タスク一覧取得
      description: 0件のときは空の配列 # 検索に対応
      operationId: Gets
      deprecated: false
      responses:
        200:
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskGetResponseDto"
    post:
      tags:
        - tasks
      summary: タスク新規作成
      operationId: Post
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskPostRequestDto"
      responses:
        201:
          description: 201 Created
  /tasks/{taskId}:
    get:
      tags:
        - tasks
      summary: タスク1件取得
      operationId: Get
      deprecated: false
      parameters:
        - in: path
          name: taskId
          required: true
          description: UUID
          schema:
            type: string
            format: uuid
            example: xxx-xxx-xxx-xxx
      responses:
        200:
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGetResponseDto"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - tasks
      summary: タスク更新
      operationId: Put
      deprecated: false
      parameters:
        - in: path
          name: taskId
          required: true
          description: UUID
          schema:
            type: string
            format: uuid
            example: xxx-xxx-xxx-xxx
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskPutRequestDto"      
      responses:
        200:
          description: 200 OK
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - tasks
      summary: タスク削除
      operationId: Delete
      deprecated: false
      parameters:
        - in: path
          name: taskId
          required: true
          description: UUID
          schema:
            type: string
            format: uuid
            example: xxx-xxx-xxx-xxx
      responses:
        200:
          description: 200 OK
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"

components:
  responses:
    BadRequest:
      description: 400 Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseDto"
            properties:
              code:
                example: 400
              message:
                example: 400 Bad Request
    Unauthorized:
      description: 401 Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseDto"
            properties:
              code:
                example: 401
              message:
                example: 401 Unauthorized
    NotFound:
      description: 404 Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseDto"
            properties:
              code:
                example: 404
              message:
                example: 404 Not Found
  schemas:
    StatusIdEnum:
      type: number
      description: ステータスIDを変換してステータスを表示する
      example: 1
      enum:
        - 1
        - 2
        - 3
    TaskGetResponseDto:
      type: object
      required:
        - title
        - status
      properties:
        title:
          type: string
          description: タイトル
          example: 本日のタスク
        description:
          type: string
          description: 詳細
          example: タスクの詳細
        due_date:
          type: string
          format: date
          description: 締切日
          example: 2024-11-18
        status_id:
          $ref: "#/components/schemas/StatusIdEnum"
        created_at:
          type: string
          format: date-time
          description: 作成日時
        updated_at:
          type: string
          format: date-time
          description: 更新日時
    TaskPostRequestDto:
      type: object
      required:
        - title
        - status
      properties:
        title:
          type: string
          description: タイトル
          example: 本日のタスク
        description:
          type: string
          description: 詳細
          example: タスクの詳細
        due_date:
          type: string
          format: date
          description: 締切日
          example: 2024-11-18
        status_id:
          $ref: "#/components/schemas/StatusIdEnum"
    TaskPutRequestDto:
      type: object
      required:
        - title
        - status
      properties:
        title:
          type: string
          description: タイトル
          example: 本日のタスク
        description:
          type: string
          description: 詳細
          example: タスクの詳細
        due_date:
          type: string
          format: date
          description: 締切日
          example: 2024-11-18
        status_id:
          $ref: "#/components/schemas/StatusIdEnum"
    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
