/*
 * ToDo Application API
 *
 * ToDoアプリのAPI設計
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class TasksApiController : ControllerBase
    { 
        /// <summary>
        /// タスク一覧取得
        /// </summary>
        /// <remarks>0件のときは空の配列</remarks>
        /// <response code="200">200 OK</response>
        [HttpGet]
        [Route("/api/v1/tasks")]
        [ValidateModelState]
        [SwaggerOperation("TasksGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Task>), description: "200 OK")]
        public virtual IActionResult TasksGet()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Task>));
            string exampleJson = null;
            exampleJson = "[ {\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n}, {\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Task>>(exampleJson)
            : default(List<Task>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// タスク新規作成
        /// </summary>
        /// <param name="taskCreate"></param>
        /// <response code="201">201 Created</response>
        [HttpPost]
        [Route("/api/v1/tasks")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("TasksPost")]
        public virtual IActionResult TasksPost([FromBody]TaskCreate taskCreate)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            throw new NotImplementedException();
        }

        /// <summary>
        /// タスク削除
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpDelete]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("TasksTaskIdDelete")]
        [SwaggerResponse(statusCode: 400, type: typeof(TasksTaskIdGet400Response), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(TasksTaskIdGet404Response), description: "404 Not Found")]
        public virtual IActionResult TasksTaskIdDelete([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(TasksTaskIdGet400Response));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(TasksTaskIdGet404Response));

            throw new NotImplementedException();
        }

        /// <summary>
        /// タスク1件取得
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpGet]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("TasksTaskIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Task), description: "200 OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(TasksTaskIdGet400Response), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(TasksTaskIdGet404Response), description: "404 Not Found")]
        public virtual IActionResult TasksTaskIdGet([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Task));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(TasksTaskIdGet400Response));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(TasksTaskIdGet404Response));
            string exampleJson = null;
            exampleJson = "{\n  \"status_id\" : \"1\",\n  \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"due_date\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"description\" : \"タスクの詳細\",\n  \"created_at\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"title\" : \"本日のタスク\"\n}";
            exampleJson = "{\n  \"code\" : 400,\n  \"message\" : \"400 Bad Request\"\n}";
            exampleJson = "{\n  \"code\" : 404,\n  \"message\" : \"404 Not Found\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Task>(exampleJson)
            : default(Task);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// タスク更新
        /// </summary>
        /// <param name="taskId">UUID</param>
        /// <response code="200">200 OK</response>
        /// <response code="400">400 Bad Request</response>
        /// <response code="404">404 Not Found</response>
        [HttpPut]
        [Route("/api/v1/tasks/{taskId}")]
        [ValidateModelState]
        [SwaggerOperation("TasksTaskIdPut")]
        [SwaggerResponse(statusCode: 400, type: typeof(TasksTaskIdGet400Response), description: "400 Bad Request")]
        [SwaggerResponse(statusCode: 404, type: typeof(TasksTaskIdGet404Response), description: "404 Not Found")]
        public virtual IActionResult TasksTaskIdPut([FromRoute (Name = "taskId")][Required]Guid taskId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(TasksTaskIdGet400Response));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(TasksTaskIdGet404Response));

            throw new NotImplementedException();
        }
    }
}
